package javaSrc;

/**
 * ignore this for now. generated by maven, probably not needed
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
    }
}
